### ISSUE TITLE
Possible to implement workaround to use this with root DNS domain?

### ISSUE THREAD

**Issue by teutat3s** [arekinath/triton-dehydrated#16]
Assume you'd like to use this in an instance that's meant to run the webserver for a root domain -
responding both to `example.com` and `www.example.com`. Is there a way to generate SSL certs for both domains with this handy dehydrated DNS hook and triton CNS?

Thanks for your continous work on this!

**Comment by jclulow** [comment]
I'm doing this on one of my servers.  I have the following (with root domain replaced with `example.com`) in `domains.txt`:

```
example.com www.example.com blog.example.com
```

Note that all of the domains are on the one line, so that we get just one certificate with three possible host names, rather than three separate certificates.

Then, in my DNS zone for `example.com` I have records like this:

```
$ORIGIN example.com.           
$TTL 60                        
                               
@                     IN A      1.2.3.4
_acme-challenge       IN CNAME  _acme-challenge.ZONE.inst.ACCOUNT.us-west-1.triton.zone.
                               
blog                  IN CNAME  ZONE.inst.ACCOUNT.us-west-1.triton.zone.
_acme-challenge.blog  IN CNAME  _acme-challenge.ZONE.inst.ACCOUNT.us-west-1.triton.zone.
 
www                   IN CNAME  ZONE.inst.ACCOUNT.us-west-1.triton.zone.
_acme-challenge.www   IN CNAME  _acme-challenge.ZONE.inst.ACCOUNT.us-west-1.triton.zone.
```

The challenge with the "root" name (`@`) is that it cannot be a `CNAME` record for a variety of disappointing but ultimately unavoidable DNS reasons.  As such, I have used an `A` record with the hard-coded IP address of the web server zone for the root, and an appropriate `CNAME` for everything else.  Note that we _can_ use a `CNAME` record for the required challenge address, because it's technically a subdomain of the root; i.e., `_acme-challenge.example.com`.

With this configuration, I'm able to use the regular `triton-dehydrated` DNS-based challenge/response mechanism to authorise the certificates.  The only downside is that you need some way other than CNS to manage the `A` record(s) for the root entry.
